import "./components/InputWraper.js"
import "./components/RegisterForm.js"
// import "../js/learning.js"
import "./components/Login-form.js";
import "./components/Navbar.js"
import "./components/Menu.js"
import "./components/Content-home.js"
import "./components/CreateCoureses.js"
import "./components/CourseList.js"
import "./components/LessonsContainer.js"
import "./components/LessonsList.js"
import "./components/RegisterCourse.js"

import "./screens/LoginScreen.js"
import "./screens/RegisterScreen.js"
import "./screens/IndexScreen.js"
import "./screens/CreateScreen.js"
import "./screens/CourseScreen.js"
import "./screens/RegisterCourseScrens.js"